### ISSUE TITLE
Callbacks / Webhooks for approval actions

### ISSUE THREAD

**Issue by dexhorthy** [humanlayer/humanlayer#60]
today, humanlayer pauses execution while waiting for human approval, but a robust system will signal to the calling code to exit, to be later resumed by a webhook. Without building an new runtime/framework for agent execution, we may be able to support some sort of callbacks semantics, provided the calling code / framework can serialize the current running program in such a way that a webhook/callback receiver can identify which program state to deserialize and pass the human feedback.

### Proposed solution

```python
callback = Callback(
   url="https://my-webhook-url"
   data={
     workflow_id: "12345",
   }
)

@hl.require_approval(callback=callback)
def multiple(a: int, b: int):
    return a * b

multiply(2,5)
```

upon approval, you'd get

```yaml
{
   fn: "some_function_to_appove",
   kwargs: { a: 2, b, 5}
   approved: boolean;
   response: string;
   # …more builtins…
   data: {
     workflow_id: "12345",
   }
}
````

what's tricky here is, how can you know the workflow id at runtime...you wouldn't hardcode it in the code, maybe it could be an env var if you have 1 process per agent and there's some orchestrator that is assigning them. 

We could probably support some kind of lambda thing to determine things at runtime...(thread id is a bad example but demonstrates the idea here)

```python
Callback(
   url=...,
   data_fn=lambda : { "workflow_id": threading.get_native_id() }
)
```

maybe even passing in the kwargs to the function in case the LLM or the framework is passing relevant identifying data to the tool call.

```python
Callback(
   url=...,
   data_fn=lambda kwargs : { "workflow_id": multipliers.get(kwargs.get("a")) }
)
```
